GET http://localhost:8009/jwt/decode
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE2ODEwMzYwMzYsImV4cCI6MTY4MTAzNjMzNiwic3ViIjoiYWRtaW4uZW1haWxAeWFuZGV4LnJ1IiwidXNlciI6eyJ1c2VybmFtZSI6ImFkbWluIiwiZW1haWwiOiJhZG1pbi5lbWFpbEB5YW5kZXgucnUiLCJyb2xlcyI6WyJST0xFX0FETUlOIl19fQ.ZGmmEjr7qRDWTPprGFQo7cqGnY_lLLLrLYTNNhLfiJc
