security:
  password_hashers:
    Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: plaintext

  providers:
    in_memory_users:
      memory:
        users:
          admin: { password: '%env(PASSWORD_ADMIN)%', roles: [ 'ROLE_ADMIN' ] }
          user: { password: '%env(PASSWORD_USER)%', roles: [ 'ROLE_USER' ] }

  firewalls:
    dev:
      pattern: ^/(css|images|js)/
      security: false
    account_admin:
      pattern: ^/admin
      json_login:
        check_path: api_account_admin
    account_user:
      pattern: ^/user
      http_basic: ~
    main:
      security: false

  access_control:
    - { path: ^/admin, roles: ROLE_ADMIN }
    - { path: ^/user, roles: ROLE_USER }