parameters:
  welcome: '%env(WELCOME)%'
  env(USERS): '%kernel.project_dir%/config/users.json'
services:
  _defaults:
    autowire: true
    autoconfigure: true
    bind:
      $users: '%env(json:file:resolve:USERS)%'

  MicroApi\:
    resource: '../src/'
    exclude:
      - '../src/Kernel.php'